### ISSUE TITLE
Error 'TypeError: 'function' object is not iterable' in function 'plot'

### ISSUE THREAD

**Issue by chanes76** [dabl/dabl#114]
Hello,

for allmost all functions of the package 'dabl' (such as 'clean' and 'plot' for example) I keep getting the following error:

```
TypeError: 'function' object is not iterable
```

This does not seem to be a problem of my specific data, because when I run the following example code (from the website):

```python
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from dabl import plot
from dabl.utils import data_df_from_bunch

wine_bunch = load_wine()
wine_df = data_df_from_bunch(wine_bunch)

plot(wine_df, 'target')
``` 

I then get the following output on my machine:

```Traceback (most recent call last):

  File "<ipython-input-61-92b3b7736897>", line 1, in <module>
    plot(wine_df, 'target')

  File "C:\Daten\Anaconda3\lib\site-packages\dabl\plot\supervised.py", line 485, in plot
    X, types = clean(X, type_hints=type_hints, return_types=True)

  File "C:\Daten\Anaconda3\lib\site-packages\dabl\preprocessing.py", line 380, in clean
    lambda x: str(x))

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\accessor.py", line 115, in f
    return self._delegate_method(name, *args, **kwargs)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\categorical.py", line 2204, in _delegate_method
    res = method(*args, **kwargs)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\categorical.py", line 940, in rename_categories
    cat.categories = new_categories

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\categorical.py", line 408, in categories
    new_dtype = CategoricalDtype(categories, ordered=self.ordered)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 154, in __init__
    self._finalize(categories, ordered, fastpath=False)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 181, in _finalize
    fastpath=fastpath)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 319, in _validate_categories
    categories = Index(categories, tupleize_cols=False)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 374, in __new__
    subarr = _asarray_tuplesafe(data, dtype=object)

  File "C:\Daten\Anaconda3\lib\site-packages\pandas\core\common.py", line 379, in _asarray_tuplesafe
    values = list(values)

TypeError: 'function' object is not iterable
```

However, when I installed dabl it did not complain (it said: 'Successfully built dabl').
Is this a bug? Is there maybe an obvious workaround so that I can still use the package?

Thank you for your time

Hannes

**Comment by amueller** [comment]
Hi @chanes76. Sorry for the slow reply. What version of pandas and scikit-learn are you using?
And what version of dabl? Please make sure you have dabl 0.1.2.

Thanks,
Andy

**Comment by amueller** [comment]
closing as no reply.
