### ISSUE TITLE
Add a multi-class precision-recall curve to explain

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#226]
Right now ``explain`` only does a precision-recall curve for binary classification, but not for multi-class classification. We should also do it for multi-class classification, I think.

**Comment by praths007** [comment]
While going through explain I wasn't able to find a plot for precision-recall of binary classification. Although, I did find roc plots for binary and multiclass classification under `plot_classification_metrics`. Is the precision-recall curve in a different location?

Also running an explain on multiclass dataset throws the following error:
```python
import numpy as np
from dabl import explain, SimpleClassifier
Backend Qt5Agg is interactive backend. Turning interactive mode on.
from sklearn.datasets import make_multilabel_classification
X, y = make_multilabel_classification(n_classes=2, n_labels=1,
                                      random_state=1)
y = np.array([sum(i) for i in y])
obj = SimpleClassifier()
obj.fit(X, y)
```
`
Running DummyClassifier(strategy='prior')
accuracy: 0.450 f1_macro: 0.207 precision_macro: 0.150 recall_macro: 0.333
=== new best DummyClassifier(strategy='prior') (using recall_macro):
accuracy: 0.450 f1_macro: 0.207 precision_macro: 0.150 recall_macro: 0.333
Running GaussianNB()
accuracy: 0.661 f1_macro: 0.507 precision_macro: 0.513 recall_macro: 0.532
=== new best GaussianNB() (using recall_macro):
accuracy: 0.661 f1_macro: 0.507 precision_macro: 0.513 recall_macro: 0.532
Running MultinomialNB()
accuracy: 0.790 f1_macro: 0.682 precision_macro: 0.734 recall_macro: 0.688
=== new best MultinomialNB() (using recall_macro):
accuracy: 0.790 f1_macro: 0.682 precision_macro: 0.734 recall_macro: 0.688
Running DecisionTreeClassifier(class_weight='balanced', max_depth=1)
accuracy: 0.651 f1_macro: 0.481 precision_macro: 0.476 recall_macro: 0.546
Running DecisionTreeClassifier(class_weight='balanced', max_depth=5)
accuracy: 0.590 f1_macro: 0.478 precision_macro: 0.489 recall_macro: 0.482
Running DecisionTreeClassifier(class_weight='balanced', min_impurity_decrease=0.01)
accuracy: 0.572 f1_macro: 0.462 precision_macro: 0.482 recall_macro: 0.465
Running LogisticRegression(C=0.1, class_weight='balanced', max_iter=1000, solver='lbfgs')
accuracy: 0.732 f1_macro: 0.620 precision_macro: 0.632 recall_macro: 0.624
Running LogisticRegression(class_weight='balanced', max_iter=1000, solver='lbfgs')
accuracy: 0.721 f1_macro: 0.590 precision_macro: 0.593 recall_macro: 0.602
Best model:
Pipeline(steps=[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))), ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])
Best Scores:
accuracy: 0.790 f1_macro: 0.682 precision_macro: 0.734 recall_macro: 0.688
Out[8]: 
SimpleClassifier(random_state=None, refit=True, shuffle=True, type_hints=None,
                 verbose=1)
`
```python
explain(obj, X, y)
```
`
Traceback (most recent call last):
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/dabl/explain.py", line 236, in _extract_inner_estimator
    feature_names)
TypeError: get_feature_names() takes 1 positional argument but 2 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-89afddff61ce>", line 1, in <module>
    explain(obj, X, y)
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/dabl/explain.py", line 125, in explain
    estimator, feature_names)
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/dabl/explain.py", line 238, in _extract_inner_estimator
    feature_names = inner_estimator.steps[0][1].get_feature_names()
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/dabl/preprocessing.py", line 609, in get_feature_names
    feature_names.extend(ohe.get_feature_names(ohe_cols))
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py", line 850, in get_feature_names
    input_features[i] + '_' + str(t) for t in cats[i]]
  File "/home/osboxes/miniconda3/envs/os_venv_py35/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py", line 850, in <listcomp>
    input_features[i] + '_' + str(t) for t in cats[i]]
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')
`

**Comment by amueller** [comment]
I'll try to investigate, sorry I'm a bit swamped right now.

**Comment by amueller** [comment]
oh, sorry, this is probably https://github.com/scikit-learn/scikit-learn/issues/16593 or at least related? the dtype of ``input_features`` is ``<U21`` which can not be concatenated
