### ISSUE TITLE
AnyClassifier preprocessing and OpenML automlbenchmark integration

### ISSUE THREAD

**Issue by hp2500** [dabl/dabl#250]
I have been trying to integrate AnyClassifier as an automl framework to https://github.com/openml/automlbenchmark in order to run experiments in a controlled environment. I feel like I have an OK grasp of the automlbenchmark repo now and have successfully integrated standalone sklearn algorithms as frameworks and ran the test benchmark. 
While I did find a way to make dabl work as well, automlbenchmark doesn't seem to play well with the dabl preprocessing functions. Here is an example traceback: 

```python
Traceback (most recent call last):
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/automlbenchmark/automlbenchmark/amlb/benchmark.py", line 420, in run
    meta_result = framework.run(self._dataset, task_config)
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/automlbenchmark/automlbenchmark/frameworks/dabl/__init__.py", line 4, in run
    return run(*args, **kwargs)
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/automlbenchmark/automlbenchmark/frameworks/dabl/exec.py", line 30, in run
    predictor.fit(X_train, y_train)
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/dabl/dabl/models.py", line 438, in fit
    types = detect_types(X, type_hints=self.type_hints)
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/dabl/dabl/preprocessing.py", line 321, in detect_types
    clean_float_string, dirty_float = _find_string_floats(
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/dabl/dabl/preprocessing.py", line 158, in _find_string_floats
    is_float = X.apply(_float_matching)
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/apply.py", line 295, in apply_standard
    result = libreduction.compute_reduction(
  File "pandas/_libs/reduction.pyx", line 620, in pandas._libs.reduction.compute_reduction
  File "pandas/_libs/reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
  File "/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl_develop/dabl/dabl/preprocessing.py", line 20, in _float_matching
    is_floaty = X_col.str.match(_FLOAT_REGEX)
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/strings.py", line 2041, in __init__
    self._inferred_dtype = self._validate(data)
  File "/miniconda3/envs/dabl_test/lib/python3.8/site-packages/pandas/core/strings.py", line 2098, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
```
My workaround consists of formatting all variables as strings before passing them to AnyClassifier() in the automlbenchmark exec.py file. However, I was surprised by the errors, since I have tested AnyClassifier() on a few datasets outside of automlbenchmark and never had similar issues. I just wanted to flag this in case you think it needs attention. I also thought about the option to add an argument to AnyClassifier(), such that users can indicate whether they want to use it with or without EasyPreprocessor(), as some users might be only interested in the portfolios and not the preprocessing part. 

Best,
Heinrich

**Comment by amueller** [comment]
Sorry for the slow reply. I'm working on fixing this issue!

**Comment by amueller** [comment]
Do you know which dataset caused this error? I'm trying to reproduce.

**Comment by amueller** [comment]
Can you check if this is fixed in master now? Thanks!
