### ISSUE TITLE
Calculating AUC with AnyClassifier... AttributeError: 'AnyClassifier' object has no attribute 'decision_function'

### ISSUE THREAD

**Issue by hp2500** [dabl/dabl#90]
It seems like it is not possible to calculate AUC scores when using AnyClassifier with sklearn.model_selection.corss_val_score. Here is a minimal example:

```python
X, y = datasets.load_breast_cancer(return_X_y=True)
sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
cross_val_score(sr, X = X, y = y, scoring = 'roc_auc', cv = 3)
```

```pytb
best classifier:  HistGradientBoostingClassifier(l2_regularization=0.0001, learning_rate=0.1,
                               loss='auto', max_bins=64, max_depth=20,
                               max_iter=400, max_leaf_nodes=128,
                               min_samples_leaf=6, n_iter_no_change=None,
                               random_state=47806, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.958
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/miniconda3/lib/python3.7/site-packages/sklearn/metrics/scorer.py in __call__(self, clf, X, y, sample_weight)
    180             try:
--> 181                 y_pred = clf.decision_function(X)
    182 

AttributeError: 'AnyClassifier' object has no attribute 'decision_function'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-18-16e17e76c51b> in <module>
      3 sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
      4 
----> 5 cross_val_score(sr, X = X, y = y, scoring = 'roc_auc', cv = 3)

/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)
    387                                 fit_params=fit_params,
    388                                 pre_dispatch=pre_dispatch,
--> 389                                 error_score=error_score)
    390     return cv_results['test_score']
    391 

/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    229             return_times=True, return_estimator=return_estimator,
    230             error_score=error_score)
--> 231         for train, test in cv.split(X, y, groups))
    232 
    233     zipped_scores = list(zip(*scores))

/miniconda3/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
    919             # remaining jobs.
    920             self._iterating = False
--> 921             if self.dispatch_one_batch(iterator):
    922                 self._iterating = self._original_iterator is not None
    923 

/miniconda3/lib/python3.7/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    757                 return False
    758             else:
--> 759                 self._dispatch(tasks)
    760                 return True
    761 

/miniconda3/lib/python3.7/site-packages/joblib/parallel.py in _dispatch(self, batch)
    714         with self._lock:
    715             job_idx = len(self._jobs)
--> 716             job = self._backend.apply_async(batch, callback=cb)
    717             # A job can complete so quickly than its callback is
    718             # called before we get here, causing self._jobs to

/miniconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py in apply_async(self, func, callback)
    180     def apply_async(self, func, callback=None):
    181         """Schedule a func to be run"""
--> 182         result = ImmediateResult(func)
    183         if callback:
    184             callback(result)

/miniconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py in __init__(self, batch)
    547         # Don't delay the application, to avoid keeping the input
    548         # arguments in memory
--> 549         self.results = batch()
    550 
    551     def get(self):

/miniconda3/lib/python3.7/site-packages/joblib/parallel.py in __call__(self)
    223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    224             return [func(*args, **kwargs)
--> 225                     for func, args, kwargs in self.items]
    226 
    227     def __len__(self):

/miniconda3/lib/python3.7/site-packages/joblib/parallel.py in <listcomp>(.0)
    223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    224             return [func(*args, **kwargs)
--> 225                     for func, args, kwargs in self.items]
    226 
    227     def __len__(self):

/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, return_estimator, error_score)
    552         fit_time = time.time() - start_time
    553         # _score will return dict if is_multimetric is True
--> 554         test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
    555         score_time = time.time() - start_time - fit_time
    556         if return_train_score:

/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _score(estimator, X_test, y_test, scorer, is_multimetric)
    595     """
    596     if is_multimetric:
--> 597         return _multimetric_score(estimator, X_test, y_test, scorer)
    598     else:
    599         if y_test is None:

/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _multimetric_score(estimator, X_test, y_test, scorers)
    625             score = scorer(estimator, X_test)
    626         else:
--> 627             score = scorer(estimator, X_test, y_test)
    628 
    629         if hasattr(score, 'item'):

/miniconda3/lib/python3.7/site-packages/sklearn/metrics/scorer.py in __call__(self, clf, X, y, sample_weight)
    186 
    187             except (NotImplementedError, AttributeError):
--> 188                 y_pred = clf.predict_proba(X)
    189 
    190                 if y_type == "binary":

AttributeError: 'AnyClassifier' object has no attribute 'predict_proba'
```

**Comment by amueller** [comment]
please format code and traceback appropriately:
Readability can be greatly improved if you [format](https://help.github.com/articles/creating-and-highlighting-code-blocks/) your code snippets and complete error messages appropriately. For example:

    ```python
    print(something)
    ```
generates:
```python
print(something)
```
And:

    ```pytb
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'hello'
    ```
generates:
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'hello'
```
You can edit your issue descriptions and comments at any time to improve readability.

This is apparently not implemented, but you can easily do so by sending a PR that does
```python
def predict_proba(self, X):
	return self.<attribute that contains final estimator>.predict_proba(X)
```

**Comment by hp2500** [comment]
Thanks for the hint! I have integrated the method as suggested: 
```python
def predict_proba(self, X):
        return self.est_.predict_proba(X)
```
I also had to set the SVC parameter probability = True, which wasn't immediately obvious to me. It seems to work now. I will send a PR shortly.

**Comment by amueller** [comment]
You shouldn't use ``probability=True``, you should add ``decision_function`` to AnyClassifier instead.

**Comment by amueller** [comment]
should be fixed.
